source/includes/_chat.md
source/includes/_event.md
source/includes/_event_list.md
source/includes/_profile.md
source/index.html.md

[code] added a new methods

---

Vagrantfile
source/includes/_playlist.md

updated playlists methods

---

source/includes/_event_list.md
source/includes/_widget.md
source/index.html.md

@excelWithBusiness/developers please review

[code] added support for widget installation guide and events structure

---

source/includes/_widget.md

Update documentation
@excelWithBusiness/backend

Add # to ID selector on example

---

source/includes/_playlist.md
source/includes/_profile.md

[code] updated documentation

---

Makefile
README.md

[code] addede jenkins makefile support

---

README.md

[code] test jenkins

---

README.md

[code] jenkins test take 2

---

docker-compose.yml

[code] slate update port

---

config.rb
docker-compose.yml

[code] routing to port 443

---

.dockerignore
Dockerfile
config.rb
docker-compose.yml

[code] make run with rancher

---

source/includes/_profile.md

Added `profile.SetAssetComplete` endpoint

Added profile.SetAssetComplete endpoint

---

docker-compose.yml
source/includes/_goal.md
source/includes/_models.md
source/index.html.md

@excelWithBusiness/developers please review

[code] added definition of models

---

source/includes/_chat.md

Added chat.IsComplete endpoint

Added chat.IsComplete endpoint

---

source/includes/_chat.md
source/includes/_event_list.md
source/includes/_goal.md
source/includes/_models.md
source/includes/_playlist.md
source/includes/_profile.md
source/index.html.md

[code] updated as per company feedback

---

source/includes/_event_list.md

docs updated for the event

---

source/includes/_event.md
source/includes/_event_list.md

Event updated launch_assetpage->asset_launch

Event updated launch_assetpage->asset_launch

---

source/includes/_event_list.md

**What I did**
- Updated event names: `asset_open` , `asset_bookmark_remove` , `asset_bookmark_add`, `asset_complete`
Section `Structure` contains request args
Review:

updated event names

---

source/includes/_event_list.md

Name updated `feedback_asset` -> `asset_feedback_add`
https://filtered-ewb.atlassian.net/browse/MAG-835

Name updated `feedback_asset` -> `asset_feedback_add`

---

source/includes/_event_list.md

Added new event doc for `open_searchbar` event
https://filtered-ewb.atlassian.net/browse/MAG-845

MAG-845 added new event doc for open_searchbar

---

source/includes/_event_list.md

event name updated -> `open_searchbar` -> `searchbar_open`

`open_searchbar` -> `searchbar_open`

---

source/includes/_goal.md

documentation updated

---

source/includes/_goal.md

order in all goals methods

---

source/includes/_user.md

Updated the endpoints for the API v2 update.

[MAG-1139] Update auth endpoints

---

source/includes/_profile.md

Added comment `It is highly suggested that the client uses the optional parameter for better reporting.` to profile.setFavouriteAsset and SetCompleteAsset

Comment added to profile.setFavouriteAsset and SetCompleteAsset

---

source/includes/_token.md
source/includes/_user.md
source/index.html.md

-  Updated documentation for user.Refresh method

MAG-1144 updated documentation for user.Refresh method

---

source/includes/_playlist.md

- spelling error - `favourite`
Please review
**JIRA Card**
https://filtered-ewb.atlassian.net/browse/MAG-1469

MAG-1469 spelling error

---

source/index.html.md

- Replaced `id` to `userID` for `user.Authenticate` method
Please review
**JIRA Card**
https://filtered-ewb.atlassian.net/browse/MAG-1461

MAG-1461 replaced id to userID

---

source/index.html.md

Updated User.Authenticate description
Please review
**Jira Card**
https://filtered-ewb.atlassian.net/browse/MAG-1459

MAG-1459 update description

---

source/includes/_playlist.md

[MAG-1496] Add FetchNexRexPlaylists method

---

source/includes/_playlist.md

Correct method name on playlist

---

source/includes/_playlist.md

Limits updated to match the code. 20 is de default and 50 is the max

---

source/includes/_playlist.md

This is the documentation for playlist.GetAsset.
https://filtered-ewb.atlassian.net/browse/MAG-1769

[MAG-1769] Add GetAsset to API documentation

---

Makefile
source/includes/_goal.md
source/includes/_playlist.md
source/includes/_profile.md
source/includes/_token.md
source/includes/_user.md

Add ECR push

---

.gitignore
source/includes/_models.md
source/includes/_playlist.md

API Docs Update with Providers

---

source/includes/_playlist.md

Update GetAsset > GetAssets
